mystery box SC
multiversx/mx-contracts-rs pull request #3
Opened 2023-06-02 11:43 UTC by psorinionut

2023-06-02 11:45 UTC, alyn509 approved these changes

2023-06-02 11:48 UTC, alyn509 requested changes

2023-06-02 11:48 UTC, alyn509 commented on contracts/mystery-box/src/config.rs
> +    // fn egld_reserve(&self) -> SingleValueMapper<BigUint>;
remove this

2023-06-02 12:07 UTC, psorinionut commented on contracts/mystery-box/src/config.rs
> +    // fn egld_reserve(&self) -> SingleValueMapper<BigUint>;
Removed unused code.

2023-06-05 13:28 UTC, sasurobert requested changes

2023-06-05 13:28 UTC, sasurobert commented on contracts/mystery-box/src/lib.rs
> +        );
Line 46-53 is not needed here. They are needed only when the reward setup is created for the overall SC

2023-06-05 13:28 UTC, sasurobert commented on contracts/mystery-box/src/lib.rs
> +        let user_payment = EsdtTokenPayment::new(
There is no need to create new NFT every time. SFTs are ok, same information, no need to duplicate in separate NFTs.

2023-06-05 13:28 UTC, sasurobert commented on contracts/mystery-box/src/lib.rs
> +            active_cooldown =
What do you want with this while code? 
The SFT of misteryBox should contain an creation epoch. And you should check only that currentepoch - creationEpoch > cooldownPeriod

2023-06-05 13:28 UTC, sasurobert commented on contracts/mystery-box/src/lib.rs
> +            winning_reward = self.get_winning_reward(&mystery_box_attributes);
You have to call this only once.

2023-06-05 13:28 UTC, sasurobert commented on contracts/mystery-box/src/lib.rs
> +        self.send().esdt_local_burn(
I do not see the code for creating a new SFT and sending that to the user

2023-06-08 09:02 UTC, alyn509 approved these changes

2023-06-08 11:02 UTC, alyn509 submitted a review, later dismissed

2023-06-09 14:22 UTC, sasurobert approved these changes

2023-06-19 15:21 UTC, sasurobert approved these changes

2023-06-19 15:24 UTC, alyn509 approved these changes

2023-06-19 15:25 UTC, merged